spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.h2.console.enabled=false
server.forward-headers-strategy=native

app.initial-user.name=${APP_USER_NAME}
app.initial-user.email=${APP_USER_EMAIL}
app.initial-user.password=${APP_USER_PASSWORD}
app.jwt.secret=${JWT_SECRET}
