spring.application.name=dev-mentor-backend
debug=false
spring.jpa.open-in-view=false
server.port=${SERVER_PORT:8080}
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
spring.flyway.enabled=true
app.jwt.expiration-millis=${JWT_EXPIRATION_MILLIS:3600000}
