CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    senha_hash VARCHAR(100) NOT NULL,
    data_criacao TIMESTAMP NOT NULL
);

CREATE TABLE tecnologia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE,
    tipo VARCHAR(20) NOT NULL,
    descricao VARCHAR(500),
    carga_horaria_planejada DOUBLE PRECISION NOT NULL,
    status VARCHAR(20) NOT NULL,
    usuario_id BIGINT NOT NULL,
    CONSTRAINT fk_tecnologia_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id),
    CONSTRAINT chk_tecnologia_carga CHECK (carga_horaria_planejada > 0)
);

CREATE TABLE conteudo_planejado (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tecnologia_id BIGINT NOT NULL,
    titulo VARCHAR(150) NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    peso INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    nivel_dominio VARCHAR(20),
    CONSTRAINT fk_conteudo_tecnologia FOREIGN KEY (tecnologia_id) REFERENCES tecnologia(id),
    CONSTRAINT chk_conteudo_peso CHECK (peso BETWEEN 1 AND 3)
);

CREATE TABLE planejamento_estudo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tecnologia_id BIGINT NOT NULL,
    data_inicio DATE NOT NULL,
    data_fim DATE NOT NULL,
    horas_planejadas_totais DOUBLE PRECISION NOT NULL,
    horas_semanais DOUBLE PRECISION NOT NULL,
    observacao VARCHAR(500),
    CONSTRAINT fk_plano_tecnologia FOREIGN KEY (tecnologia_id) REFERENCES tecnologia(id),
    CONSTRAINT chk_plano_datas CHECK (data_fim > data_inicio),
    CONSTRAINT chk_plano_horas CHECK (horas_planejadas_totais > 0 AND horas_semanais > 0)
);

CREATE TABLE registro_estudo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tecnologia_id BIGINT NOT NULL,
    conteudo_id BIGINT,
    data_estudo DATE NOT NULL,
    tipo_estudo VARCHAR(20) NOT NULL,
    tempo_minutos INTEGER NOT NULL,
    observacoes VARCHAR(500),
    CONSTRAINT fk_registro_tecnologia FOREIGN KEY (tecnologia_id) REFERENCES tecnologia(id),
    CONSTRAINT fk_registro_conteudo FOREIGN KEY (conteudo_id) REFERENCES conteudo_planejado(id),
    CONSTRAINT chk_registro_tempo CHECK (tempo_minutos > 0)
);

CREATE TABLE projeto_pessoal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    stack VARCHAR(200) NOT NULL,
    status VARCHAR(30) NOT NULL,
    proximo_passo VARCHAR(300),
    tecnologia_id BIGINT,
    usuario_id BIGINT NOT NULL,
    CONSTRAINT fk_projeto_tecnologia FOREIGN KEY (tecnologia_id) REFERENCES tecnologia(id),
    CONSTRAINT fk_projeto_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id)
);

CREATE INDEX idx_conteudo_tecnologia ON conteudo_planejado(tecnologia_id);
CREATE INDEX idx_plano_tecnologia ON planejamento_estudo(tecnologia_id);
CREATE INDEX idx_registro_tecnologia ON registro_estudo(tecnologia_id);
CREATE INDEX idx_registro_data ON registro_estudo(data_estudo);
